"""add_role_to_users

Revision ID: 6ca9a7150205
Revises: 89fb53c8c3da
Create Date: 2026-02-27 15:46:53.697447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca9a7150205'
down_revision: Union[str, Sequence[str], None] = '89fb53c8c3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add nullable first
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # Update existing users to 'user'
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")
    # Make it non-nullable
    op.alter_column('users', 'role', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
