"""Add source and page metadata

Revision ID: bb45f220e7b9
Revises: 9c994f85448a
Create Date: 2026-02-22 11:12:05.039789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb45f220e7b9'
down_revision: Union[str, Sequence[str], None] = '9c994f85448a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'page')
    op.drop_column('documents', 'source')
    # ### end Alembic commands ###
